name: Build Template

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Имя Docker-образа (без юзернейма, например: my-app)'
        required: true
        type: string
      work_dir:
        description: 'Директория с проектом и Dockerfile (например: back или front)'
        required: true
        type: string
      api_url:
        description: 'URL API для фронтенда'
        required: false
        type: string
        default: ""
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASS:
        required: true

jobs:
  build_image:
    name: Build and Push (${{ inputs.image_name }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        env:
          IMAGE_BASE: ${{ secrets.DOCKER_USER }}/${{ inputs.image_name }}
          API_URL: ${{ inputs.api_url }}
          WORK_DIR: ${{ inputs.work_dir }}
        run: |
          # Переходим в нужную подпапку перед сборкой
          cd $WORK_DIR
          
          # Формируем строку с build-args, если api_url не пустой
          BUILD_ARGS=""
          if [ -n "$API_URL" ]; then
            BUILD_ARGS="--build-arg VITE_API_URL=$API_URL"
          fi
          
          # Собираем образ (точка в конце теперь указывает на папку back или front)
          docker build $BUILD_ARGS -t $IMAGE_BASE:sha-${{ github.sha }} -t $IMAGE_BASE:latest .
          
          # Пушим
          docker push $IMAGE_BASE:sha-${{ github.sha }}
          docker push $IMAGE_BASE:latest