name: Deploy to YC Managed K8s Template

on:
  workflow_call:
    inputs:
      image_tag:
        description: "Docker image tag (e.g. sha-xxxx)"
        required: true
        type: string
    secrets:
      YC_SA_JSON_CREDENTIALS:
        required: true

jobs:
  deploy_to_k8s:
    name: Deploy to Managed K8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout GitOps repo for Helm charts
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/devops-gitops
          path: gitops

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Configure Yandex Cloud Profile
        env:
          YC_SA_KEY: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        run: |
          echo "$YC_SA_KEY" > /tmp/sa-key.json
          yc config profile create sa-profile || true
          yc config set service-account-key /tmp/sa-key.json
          yc config set folder-id ${{ vars.YC_FOLDER_ID }}

      - name: Configure kubectl
        run: |
          yc managed-kubernetes cluster get-credentials \
            --id ${{ vars.K8S_CLUSTER_ID }} \
            --external \
            --force

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Application with Helm
        env:
          REG_URL: "cr.yandex/${{ vars.YC_REGISTRY_ID }}"
          TAG: ${{ inputs.image_tag }}
        run: |
          helm upgrade --install myapp ./gitops/helm/myapp \
            --namespace homework \
            --reuse-values \
            --set backend.image.repository="$REG_URL/todo-back" \
            --set backend.image.tag="$TAG" \
            --set frontend.image.repository="$REG_URL/todo-front" \
            --set frontend.image.tag="$TAG" \
            --wait \
            --timeout 5m

      - name: Cleanup Key
        if: always()
        run: rm -f /tmp/sa-key.json
