name: PR Check

on:
  pull_request:
    branches: [week*]
  workflow_call:

jobs:
  checks:
    uses: ./.github/workflows/typecheck.yaml
    strategy:
      fail-fast: false
      matrix:
        service: [back, front]
    with:
      service: ${{ matrix.service }}
